export enum ActionTypes {
  CREATE_TASK = 'CREATE_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  DELETE_TASK = 'DELETE_TASK',
  DUPLICATE_TASK = 'DUPLICATE_TASK',
  TOGGLE_TASK_COMPLETED_STATE = 'TOGGLE_TASK_COMPLETED_STATE',
}
